### ISSUE TITLE
Creating Google Service Account no longer exist

### ISSUE THREAD

**Issue by phillihoch** [expo/fyi#132]
https://github.com/expo/fyi/blob/main/creating-google-service-account.md

The tutorial no longer exists.
Google updated something and this screen is shown:
<img width="1483" alt="image" src="https://github.com/expo/fyi/assets/64873861/bb625fd9-42d3-429b-85b4-85eb92120a98">

**Comment by AlexanderCollins** [comment]
At first glance it looks like the new process is to create a Google Cloud Platform project which you then link to the App in Google Play Console under the "App Integrity" menu item. Then to "Integrate the Integrity API" there is a button that leads to  [**Google Plat Integrity API** > **Setup**](https://developer.android.com/google/play/integrity/setup). There it reads:

> Set up in Google Play Console (recommended)
By enabling Play Integrity API responses in the [Google Play Console](http://play.google.com/console), you will gain access to additional configuration options, testing features, and API reporting. This option is only available to apps distributed on Google Play. Navigate to Release > App integrity. Under Play Integrity API select Link a Cloud project. Choose the Cloud project you want to link to your app and this will enable Play Integrity API responses. You can now integrate the Play Integrity API into your app.

> Set up in Google Cloud Console
In your [Google Cloud Console](https://console.cloud.google.com/), create a new Cloud project or choose an existing Cloud project that you want to use with the Play Integrity API. Navigate to APIs and services. Select enable APIs and services. Search for [Play Integrity API](https://console.cloud.google.com/marketplace/product/google/playintegrity.googleapis.com) and then enable it. You can now integrate the Play Integrity API into your app.

Its a little strange that they have **Setup in google play console (recommended)** and then during the setup in GPC redirect back to the documentation that then requires you to setup in Google Cloud Console....

Anyway, continuing with **Set up in Google Cloud Console**: Navigate to the GCC project that you linked to your app and enable the [Google Play Integrity API ](https://console.cloud.google.com/marketplace/product/google/playintegrity.googleapis.com). Mine was already enabled so perhaps this step isn't required and is done by the linking. Make sure you have the correct GCP project selected in the project selection drop down at the top of the screen.

Once enabled you should be able to click **Manage** on the [**Google Play Integrity API** Page](https://console.cloud.google.com/marketplace/product/google/playintegrity.googleapis.com) (again make sure you have the right project selected if you have multiple GCP projects). 

![Screenshot 2023-10-08 at 2 47 31 pm](https://github.com/expo/fyi/assets/9352153/f70bd4a9-ac79-457a-af9b-e255cb165fa4)


This will take you to the Google Play Integrity API Service Details page. You can click the button in the banner. 

![Screenshot 2023-10-08 at 2 47 46 pm](https://github.com/expo/fyi/assets/9352153/1a5dacf3-6d9f-4c82-bb23-450fc2914f93)

If you don't have the **Create Credentials** banner button you can either go to **Credentials** > **+ Create Credentials** > **Help me choose** or  follow this link to get there: [https://console.cloud.google.com/apis/credentials/wizard](https://console.cloud.google.com/apis/credentials/wizard).

This will take you through to the Credentials Wizard. Ultimately you need a Service Details account so you can make sure the **Google Play Integrity API** is Selected and select the **Application data option**. If you were to select the user data option you would be setting up OAuth credentials which isn't what we want.

If you don't have the **Create Credentials** banner button you can either go to **Credentials** > **+ Create Credentials** > **Help me choose** or  follow this link to get there: [https://console.cloud.google.com/apis/credentials/wizard](https://console.cloud.google.com/apis/credentials/wizard).

The wizard is a weird screen because you can select **Done** but it'll do nothing. You need to select **Next** which will then redirect you to create the service account.

![Screenshot 2023-10-08 at 2 56 21 pm](https://github.com/expo/fyi/assets/9352153/a5b1e67f-0ada-49f8-9bd1-fb4ffd825dfc)

Then you'll be on the create service account page which you can also just get to from here: [https://console.cloud.google.com/iam-admin/serviceaccounts/create](https://console.cloud.google.com/iam-admin/serviceaccounts/create)

Name your service account and then click **Create and Continue**.

![Screenshot 2023-10-08 at 2 59 50 pm](https://github.com/expo/fyi/assets/9352153/1f58acb2-3903-4829-8a76-c0c9d42f36a2)

At this point you need to **Grant this service account access to project**. I'm not sure what the granular permissions need to be. I advise against using broad administrative permissions just on the basis that I don't know what the security implications may be however for my purposes I selected the **Owner** role and then clicked **Continue**.

Then I clicked **Done**, ignoring the 3rd step.
![Screenshot 2023-10-08 at 3 17 21 pm](https://github.com/expo/fyi/assets/9352153/af01c167-7880-4508-9475-97014b4091ed)

You should be redirected to your new service account however if your not just head to [Service Accounts](https://console.cloud.google.com/iam-admin/serviceaccounts) or [Credentials](https://console.cloud.google.com/apis/credentials) to find it.

Then once you are on your new service account's page click the **Keys** tab > **Add Key** dropdown > **Create new key** option.

![Screenshot 2023-10-08 at 3 20 44 pm](https://github.com/expo/fyi/assets/9352153/33036658-5ea1-45ce-b2ff-ae235813eb8c)

A modal will appear **Create private key for "<your project>"**. Select **JSON** and then **Create**.

![Screenshot 2023-10-08 at 3 22 31 pm](https://github.com/expo/fyi/assets/9352153/fbd3c812-544c-47ee-b684-96236a30bb0e)

The private key will automatically download and will be named "projectname-first12charactersofkeyname.json".

Also make sure you have [**Google Play Android Developer API**](https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com) enabled too. Your service account (if it has permission) will be able to use this api automatically.

Then all I did was specify the location of the service account JSON credential file when calling `npx eas build -p android`.


This is my first time using google cloud to deploy on Android so please correct anything I've missed!

**Comment by MarcosHenriqueLordelo** [comment]
Followed the steps above but i am getting this error when trying to submit my application:
 [!] Google Api Error: Invalid request - The caller does not have permission

**Comment by vmingam** [comment]
> Followed the steps above but i am getting this error when trying to submit my application: [!] Google Api Error: Invalid request - The caller does not have permission

@MarcosHenriqueLordelo,

I've just succeeded. Few more steps are missing, linked to "... (if it has permission) ..." mentioned in the steps detailed by @AlexanderCollins https://github.com/expo/fyi/issues/132#issuecomment-1751917443

## In the Google Play Console > **Users & Permissions**

- Click on **Invite new users** 
- Add the email address of the new Service Account
- Give to him the _Admin_ permissions (_Release_ permissions seem insufficient)

Hope this is helping you.

**Comment by amandeepmittal** [comment]
Thank you, everyone, for your input, and I apologize for both the inconvenience caused and not being able to get back to you during that time. Since this issue was opened, we've reviewed and updated the guide internally. For that reason, I'm going to close this issue but if you folks think it is needs an update or i missing something, let us know!
