### ISSUE TITLE
creating-google-service-account.md is out of date

### ISSUE THREAD

**Issue by tatsutron** [expo/fyi#68]
I'm not sure where the problem lies exactly (I've been back and forth with Google support for about a week now trying to get to the bottom of it), but there seems to be some problem with this tutorial. After starting from a blank slate and following each step, at step 8 (`Return to the API access page on the Google Play Console and ensure it shows your new service account. Click on Grant access for the newly added service account.`), the service account does not appear.

**Comment by flexbox** [comment]
Hey @tatsutron 

> the service account does not appear.
I fall into the same situation as you.

Then I decided to retry and it worked.

Have you double-check that you have done step 2.

```
Service Accounts > Service Account User
```

![image](https://user-images.githubusercontent.com/360936/177784943-315fc26a-5790-475f-a307-d29fec24d873.png)


If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
