### ISSUE TITLE
Npm start problem

### ISSUE THREAD

**Issue by Numanpaf885** [expo/fyi#83]
I have this problem when i run **npm start**
-------------------------------------
I am a begginer coding and i was creating a create-react-app by watching a tutorial all was alright but i don't know why but i can't run the command `npm start` it gives me error here is what it says i tried my best.

    `PS C:\Users\User\OneDrive\Documents\react\react-app> npm start
    npm ERR!
    npm ERR! Did you mean one of these?
    npm ERR!     npm star # Mark your favorite packages
    npm ERR!     npm stars # View packages marked as favorites
    npm ERR!
    npm ERR! To see a list of scripts, run:
    npm ERR!   npm run
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-08-22T15_25_54_912Z-debug-0.log`

Here is the pakage.json

![Captura de pantalla (38)](https://user-images.githubusercontent.com/111880712/186202352-de5f8284-5e46-4daa-94ec-40f06fdefe3f.png)

    
Here is a problem screenshot, it can be more usefull
![problem screenshot](https://user-images.githubusercontent.com/111880712/186200735-ba5c9d75-641e-4870-9542-e7bb12076084.png)

here is my node and npm version:
- node: v18.6.0
- npm: v8.13.2

can anyone help me to fix it please.

**Comment by flexbox** [comment]
Hey @Numanpaf885 

I think you can read the output of your terminal

![image](https://user-images.githubusercontent.com/360936/186613039-2d96ab4c-3c10-4d15-9f9c-78b2b05599d2.png)

and it raises an error because you have nothing to run 😅 

you should at least have one entry `scripts`
```
  "scripts": {
    "start": "expo start",
    ...
  },
```

[here is an example](https://github.com/flexbox/react-native-bootcamp/blob/main/hackathon/spacecraft/package.json#L3)

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by brentvatne** [comment]
hi there! it looks like this is a question about create-react-app and unrelated to expo. you may want to refer to this repository: https://github.com/facebook/create-react-app
